baseURL: "https://gabriellazcano.com"
languageCode: "en-us"
title: "Gabriel Lazcano"
copyright: "© 2021 Gabriel Lazcano"

params:
  author: "Gabriel Lazcano"
  codepenUser: "DatsGabs"

menu:
    blog:
        - identifier: archive
          name: Archive
          url: /archive
          weight: 30
        - identifier: categories
          name: Categories
          url: /categories
          weight: 20
        - identifier: tags
          name: Tags
          url: /tags
          weight: 10
        - identifier: newsletter
          name: Newsletter
          url: /newsletter
          weight: 40

    main:
        - identifier: about
          name: About
          url: /about
          weight: 10
        - identifier: portfolio
          name: Portfolio
          url: /portfolio
          weight: 20

pygmentsUseClasses: true
